### ISSUE TITLE
Can not run on nightly: error: options `-C embed-bitcode=no` and `-C lto` are incompatible

### ISSUE THREAD

**Issue by EvanCarroll** [japaric/stack-sizes#11]
Currently I'm getting 

> error: options `-C embed-bitcode=no` and `-C lto` are incompatible

When I run this,

```text
❯ cargo stack-sizes --bin main
   Compiling asdf v0.1.0 (/tmp/asdf)
error: options `-C embed-bitcode=no` and `-C lto` are incompatible
```

**Comment by EvanCarroll** [comment]
`-c lto` seems to be something you're hard coding

https://github.com/japaric/stack-sizes/blob/6de849728bd6092b86f73025decd03d53e323414/src/bin/cargo-stack-sizes.rs#L116

[And on rustc's newer than 1.45, the option to turn `embed-bitcode` off was provided, which cargo makes use of.](https://doc.rust-lang.org/rustc/codegen-options/index.html#embed-bitcode)

> The use of -C embed-bitcode=no can significantly improve compile times and reduce generated file sizes if your compilation does not actually need bitcode (e.g. if you're not compiling for iOS or you're not performing LTO). For these reasons, **Cargo uses -C `embed-bitcode=no` whenever possible.** Likewise, if you are building directly with rustc we recommend using -C embed-bitcode=no whenever you are not using LTO.

**Comment by japaric** [comment]
thanks for your interest in this project. this project has been superseded by [`cargo-call-stack`](https://github.com/japaric/cargo-call-stack) and it's no longer maintained. if you would like to implement a stack usage analysis tool like `stack-sizes` I would recommend using `cargo-call-stack` as a reference.

the last known nigthly version that `stack-sizes` it's known to work with is `nightly-2019-03-29`; there are no plans to update `stack-sizes` to work with newer nightlies

**Comment by japaric** [comment]
no longer applies as tools have been removed (`cargo-call-stack` can deal with this change in the LTO flag)
